[workspace]
authors = ["Ali Abul Hawa <ali_abulhawa@outlook.com>"]
channels = ["conda-forge"]
name = "anomaly-detection"
platforms = [{ platform = "linux-64", cuda = "12.9" }]
version = "0.1.0"

[dependencies]
python = "3.12.*"
pytorch-gpu = ">=2.12.1,<3"
torchvision = ">=0.27,<0.28"
cuda-version = "12.9.*"
ipykernel = ">=7.3.0,<8"
ruff = ">=0.15.20,<0.16"
opencv = ">=4.12.0,<5"
pandas = ">=3.0.3,<4"
matplotlib = ">=3.11.0,<4"
seaborn = ">=0.13.2,<0.14"
